# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'v2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Hide_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Hide_Button.setGeometry(QtCore.QRect(480, 360, 131, 51))
        self.Hide_Button.setObjectName("Hide_Button")
        self.frame_everything = QtWidgets.QFrame(self.centralwidget)
        self.frame_everything.setGeometry(QtCore.QRect(20, 50, 751, 501))
        self.frame_everything.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_everything.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_everything.setObjectName("frame_everything")
        self.Score_label = QtWidgets.QLabel(self.frame_everything)
        self.Score_label.setGeometry(QtCore.QRect(470, 50, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.Score_label.setFont(font)
        self.Score_label.setObjectName("Score_label")
        self.quest_label = QtWidgets.QLabel(self.frame_everything)
        self.quest_label.setGeometry(QtCore.QRect(50, 50, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.quest_label.setFont(font)
        self.quest_label.setObjectName("quest_label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_everything)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 280, 211, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Var1 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Var1.setObjectName("Var1")
        self.verticalLayout.addWidget(self.Var1)
        self.Var2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Var2.setObjectName("Var2")
        self.verticalLayout.addWidget(self.Var2)
        self.Var3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Var3.setObjectName("Var3")
        self.verticalLayout.addWidget(self.Var3)
        self.Var4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Var4.setObjectName("Var4")
        self.verticalLayout.addWidget(self.Var4)
        self.Var2.raise_()
        self.Var3.raise_()
        self.Var4.raise_()
        self.Var1.raise_()
        self.frame_everything.raise_()
        self.Hide_Button.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Hide_Button.setText(_translate("MainWindow", "Hide"))
        self.Score_label.setText(_translate("MainWindow", "Score: "))
        self.quest_label.setText(_translate("MainWindow", "TextLabel"))
        self.Var1.setText(_translate("MainWindow", "PushButton"))
        self.Var2.setText(_translate("MainWindow", "PushButton"))
        self.Var3.setText(_translate("MainWindow", "PushButton"))
        self.Var4.setText(_translate("MainWindow", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
